name: Add labels to inactive issues
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4
        with:
          days-before-issue-stale: 180
          days-before-pr-stale: -1
          days-before-issue-close: -1
          days-before-pr-close: -1
          stale-issue-label: "needs-triage"
          operations-per-run: 300
          stale-issue-message: ""
          stale-pr-message: ""
